config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  get 'reviews/create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'cocktails#index'
  resources :cocktails, only: %i[index new create show destroy] do
    resources :doses, only: %i[new create]
    resources :reviews, only: %i[new create]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_many :reviews, dependent: :destroy
  has_many :ratings, through: :reviews
  has_one_attached :photo
  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, :cocktail_id, :ingredient_id, presence: true
  validates_uniqueness_of :cocktail_id, scope: :ingredient_id
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail

  validates :rating, inclusion: { in: 0..5 }
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to @cocktail, notice: "Your cocktail was added!"
    else
      render :new
    end
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
  redirect_to cocktails_path
  end

  def score
    # @cocktail.ratings
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @dose = Dose.new
    find_cocktail
  end

  def create
    find_cocktail
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def find_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def dose_params
    params.require(:dose).permit(:ingredient_id, :description)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @review = Review.new(review_params)
    @review.cocktail = @cocktail
    if @review.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/_card.html.erb
<div class="cards-list">
    <% @cocktails.each do |cocktail| %>
      <%= link_to cocktail_path(cocktail) do %>
        <div class="card">
          <% if cocktail.photo.attached? %>
            <div class="card_image"><%= cl_image_tag cocktail.photo.key, width: 250, height: 250, crop: :fill %></div>
          <% else %>
            <div class="card_image"><%= image_tag 'https://images.immediate.co.uk/production/volatile/sites/30/2020/08/mojito-cocktails-814a3f7.jpg?quality=90&resize=500%2C454' %></div>
          <% end %>
          <div class="card_image"><%= @photo_param %></div>
          <div class="card_title title-white">
            <p> <%= cocktail.name %> </p>
            <p>
              <% #cocktail.ratings.to_i.times do  %>
               <!-- <span class="glyphicon glyphicon-star"></span> -->
              <% #end %>
            </p>
          </div>
        </div>
      <% end %>
    <% end %>
</div>

app/views/cocktails/_carousel.html.erb
<div id="carouselExampleControls" class="carousel slide m-3" data-ride="carousel">
  <div class="carousel-inner">
    <% @cocktails.each_with_index do |cocktail, i| %>
    <div class="carousel-item <%= "active " if i==0 %>">
      <% if cocktail.photo.attached? %>
        <div class="col d-flex justify-content-center"><%= cl_image_tag cocktail.photo.key, width: 900, height: 350, crop: :fill %></div>
      <% else %>
        <%= image_tag 'https://images.immediate.co.uk/production/volatile/sites/30/2020/08/mojito-cocktails-814a3f7.jpg?quality=90&resize=500%2C454' %>
      <% end %>
    </div>
    <% end %>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/cocktails/_form.html.erb
<%= simple_form_for @cocktail do |f| %>
  <%= f.input :name, label: "Cocktail name", error: "You must specify a name!" %>
  <%= f.submit "Add your ingredients"  %>
<%= end %>

app/views/cocktails/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand d-flex align-items-center" do %>
    <%= image_tag "cocktails.png" %>
    <p><%= "What're we drinking?" %></p>
  <% end %>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Add a drink", new_cocktail_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</div>

app/views/cocktails/create.html.erb
<h1>Cocktails#create</h1>
<p>Find me in app/views/cocktails/create.html.erb</p>

app/views/cocktails/index.html.erb
<%= render "carousel" %>

<%= render "card" %>

app/views/cocktails/new.html.erb
<h1>Add a cocktail</h1>

<div class="form">
  <%= simple_form_for @cocktail do |f| %>
    <%= f.input :name, label: "Cocktail name", error: "You must specify a name!" %>
    <%= f.input :photo, as: :file, label: "Add a photo" %>
    <%= f.submit "Add your ingredients"  %>
  <% end %>
</div>

app/views/cocktails/show.html.erb
<div class="container d-flex justify-content-between">
  <div class="drink-title">
    <% if @cocktail.photo.attached? %>
      <%= cl_image_tag @cocktail.photo.key, width: 250, height: 250, crop: :fill %>
    <% else %>
      <%= image_tag 'https://images.immediate.co.uk/production/volatile/sites/30/2020/08/mojito-cocktails-814a3f7.jpg?quality=90&resize=500%2C454' %>
    <% end %>
    <h3> <%= @cocktail.name %>
       <%= link_to cocktail_path(@cocktail), method: :delete, data: { confirm: "Are you sure?" } do %>
            <i class="fa fa-trash destroy_dose"></i>
          <% end %>
    </h3>
  </div>

  <div class="ingredients">
    <h4>Ingredients
      <%= link_to new_cocktail_dose_path(@cocktail) do %>
        <i class="fas fa-plus"></i>
      <% end %>
    </h4>
    <% @cocktail.doses.each do |dose| %>

      <tr>
        <td><%= dose.ingredient.name %></td>
        <td><%= dose.description %></td>
        <td>
          <%= link_to dose_path(dose), method: :delete, data: { confirm: "Are you sure?" } do %>
            <i class="fa fa-trash destroy_dose"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
  </div>

  <div class="reviews">
    <h4>Reviews
      <%= link_to new_cocktail_review_path(@cocktail) do %>
        <i class="fas fa-plus"></i>
      <% end %>
    </h4>
    <ul>
      <% @cocktail.reviews.each do |review| %>
        <li> <%= review.content %> </li>
      <% end %>
    </ul>


  </div>
</div>

app/views/doses/create.html.erb
<h1>Doses#create</h1>
<p>Find me in app/views/doses/create.html.erb</p>

app/views/doses/destroy.html.erb
<h1>Doses#destroy</h1>
<p>Find me in app/views/doses/destroy.html.erb</p>

app/views/doses/new.html.erb
<h1>Add your ingredients!</h1>

<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.association :ingredient %>
  <%= f.input :description, label: "How much?", error: "You must specify this field" %>
  <%= f.submit "Submit"  %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">


    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar navbar-expand-sm navbar-lewagon">
      <%= link_to root_path, class: "navbar-brand d-flex align-items-center" do %>
        <%= image_tag "cocktails.png" %>
        <p><%= "What're we drinking?" %></p>
      <% end %>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "Add a drink", new_cocktail_path, class: "nav-link", :style=>'color: rgb(155, 136, 22);' %>
          </li>
        </ul>
      </div>
    </div>

    <%= yield %>
  </body>
</html>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<h3>Add a review</h3>


  <%= simple_form_for [@cocktail, @review] do |f| %>
    <%= f.input :rating, label: "Cocktail rating" %>
    <%= f.input :content, label: "Review" %>
    <%= f.submit "Add your review"  %>
  <% end %>